EPFL-ENAC/CCFatiguePlatform

- .github/workflows/frontend.yml
Inject CI prepared by David T.
> ci: frontend

- Preprocessing/tst_data_lib.py
> ✨ (preprocessing validation): check experiment folder naming

- .github/ISSUE_TEMPLATE/dataset_integration_request.yml
> ✨ (GH Issue template): for new dataset integration

- .github/ISSUE_TEMPLATE/dataset_integration_request.yml
Fixed layout in New Dataset Issue template
> 🐛 (GH Issue template): fixed layout

- Data/AGG_Data_Convention.md
- Data/CYC_Data_Convention.md
- Data/DAS_Data_Convention.md
- Data/FAF_Data_Convention.md
- Data/variables_dictionary.md
First draft, not sure about some variable like "damage" name and description and in which module should we use reliability_level (P(N)) or confidence_interval (rsql)
> :memo: (Data var_dict) Apply Tassos corrections

- .github/ISSUE_TEMPLATE/feature_request.yml
For the researcher to be able to request some new features.
Split into
- Database feature
- Analysis feature
- other
FIX #95
> ✨ (Github issue template): new feature requests

- Data/AGG_Data_Convention.md
- Data/CLD_Data_Convention.md
- Data/CYC_Data_Convention.md
- Data/DAS_Data_Convention.md
- Data/FAF_Data_Convention.md
- Data/LDS_Data_Convention.md
- Data/SNC_Data_Convention.md
- Data/variables_dictionary.md
Check consistency between data conventions and variable dictionary
> 72 variables consistency validation

- Makefile
- README.md
- backend/.gitignore
- backend/Makefile
- backend/README.md
- backend/alembic/README
- backend/ccfatigue/config.py
- backend/ccfatigue/settings.toml
- backend/poetry.lock
- backend/preprocessing/README.md
- backend/pyproject.toml
- frontend/Makefile
- frontend/README.md
Have a Makefile at the root of the project that offers : 
- `make install` that runs all necessary installations
- `make dev-*` that runs everything for dev environment
- `make run` that runs all stuffs in docker services
FIX #36
> 📝 (README and Makefile): review and cleanup

- .github/ISSUE_TEMPLATE/bug_report.yaml
Add Github issue template for bug report.
FIX #106
> feat(Github issue template): bug report

- .github/ISSUE_TEMPLATE/bug_report.yaml
bug default assignees = sbancal
> fix(github bug issue template): default assignees

- Data/DAS_Data_Convention.md
Correct CLD copy/paste into CLD
> fix(data DAS convention): correct CSV standard

- backend/ccfatigue/modules/cld_harris.py
> fix(mod 3 harris): fix missing rows output

- backend/preprocessing/tst_data_lib.py
FIX #139
Detect when XLS file is completely different from what is expected. Only 1 specific case.
> feat(dataset checker): detect complete file inconsistency (1 case)

- frontend/src/views/TestsDashboard.vue
> fix(TestsDashboard): no error when arriving to that page

- frontend/src/store/experiments.js
- frontend/src/views/DataUpload.vue
- frontend/src/views/SearchDatabase.vue
> chore(eslint): allow console.error for special cases

- frontend/src/views/TestsDashboard.vue
> feat(dashboards): add units to graphs (FA and QS)

- backend/preprocessing/hysteresis_loops.py
> feat(N_fail): process real value while creating HYS_ files

- backend/.dockerignore
- backend/.gitignore
- backend/Dockerfile
> fix(docker): fix fortran compilation inside Docker

- docker-compose.yml
> fix(docker): database restart unless stopped

- Data/variables_dictionary.md
- backend/ccfatigue/analysis/cld_harris.py
- backend/ccfatigue/analysis/cld_piecewiselinear.py
- backend/ccfatigue/analysis/cld_utils.py
- backend/ccfatigue/analysis/das_piecewiselinear.py
- backend/ccfatigue/analysis/piecewiselinear_utils.py
- backend/tests/test_analysis.py
> feat(analysis): add mod3+5 piecewise linear algo

- Data/SNC_input3.json
- Data/SNC_input4.json
- Data/SNC_inputA.json
- backend/ccfatigue/analysis/faf_ftpf.py
- backend/ccfatigue/analysis/faf_hashin_rotem.py
- backend/ccfatigue/analysis/utils/faf.py
- backend/tests/test_analysis.py
Add python version of fortran Fatigue Failure Hashin Rotem algorithm
FIX 179
> feat(backend analysis): add faf_hashinrotem algo

- backend/ccfatigue/experiment/common.py
- backend/ccfatigue/experiment/fatigue.py
- backend/ccfatigue/experiment/quasi_static.py
- backend/init_db.py
- backend/preprocessing/hysteresis_loops.py
- frontend/src/backend/model/FatigueTest.js
- frontend/src/views/TestsDashboard.vue
- openapi.json
add to right box:
- stress at failure
- strain at failure
- cycle at failure
- run out
- R
> 130 fa right box fields fix

- backend/ccfatigue/model.py
- frontend/src/backend/model/SnCurveMethod.js
- frontend/src/components/analysis/SnCurve.vue
- openapi.json
Removed unimplemented method Whitney from S-N Curve module
FIX #204
> fix(frontend analysis): remove SNC Whitney

- README.md
- frontend/src/views/AboutView.vue
Add David Tang and Nicolas Dubois in contributors list (about & readme)
FIX #202
> docs(contributors): add missing contributors

- backend/preprocessing/tst_data_lib.py
- frontend/src/views/DataUpload.vue
> docs(data upload): link to data convention from the outset

- frontend/src/components/charts/DoubleChart.vue
- frontend/src/components/charts/SimpleChart.vue
- frontend/src/utils/formatters.js
- frontend/src/views/TestsDashboard.vue
> feat(Dashboard): format numbers to engeneering notation

- frontend/src/views/TestsDashboard.vue
> fix(QS Dashboard): fix inverted x y axis

- backend/ccfatigue/experiment/fatigue.py
- backend/ccfatigue/experiment/quasi_static.py
- frontend/src/backend/model/FatigueTest.js
- frontend/src/backend/model/QuasiStaticTest.js
- frontend/src/views/TestsDashboard.vue
- openapi.json
> feat(Dashboard plots): set serie's names to specimen_name

- frontend/src/components/analysis/FatigueFailure.vue
> fix(frontend analysis): use log for FAF x-axis

- backend/ccfatigue/analysis/cyc_rangemean.py
- backend/ccfatigue/analysis/cyc_rangepair.py
- backend/ccfatigue/analysis/cyc_simplified_rainflow.py
- backend/ccfatigue/analysis/cyc_simplifiedrainflow.py
- backend/ccfatigue/analysis/utils/cyc.py
- backend/ccfatigue/analyzer.py
- backend/ccfatigue/model.py
- backend/tests/test_analysis.py
- frontend/src/backend/model/CycleCountingMethod.js
- openapi.json
> Feat/189 analysis CYC add SimplifiedRainflow and RangePair

- backend/ccfatigue/analyzer.py
- backend/ccfatigue/model.py
- backend/ccfatigue/routers/analysis.py
- frontend/src/backend/README.md
- frontend/src/backend/api/AnalysisApi.js
- frontend/src/backend/model/CldMethod.js
- frontend/src/backend/model/DamageSummationMethod.js
- frontend/src/components/analysis/CldAnalysis.vue
- openapi.json
> feat(frontend analysis): add piecewiselinear

- frontend/src/components/analysis/DamageSummation.vue
- frontend/src/components/analysis/SnCurve.vue
> fix(frontend analysis): fix labels and log axis

- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/analysis/CldAnalysis.vue
FIX #225
I used groupBy from lodash, maybe there is a simpler way of doing it.
> fix(frontend analysis): plot cld groupby cycles

- frontend/src/components/charts/SimpleChart.vue
> feat(graphs): make all graph zoomable

- backend/.pre-commit-config.yaml
- docker-compose.yml
- traefik.yaml
> [SECURITY] traefik disable old tls and ciphers

- backend/.pre-commit-config.yaml
- docker-compose.yml
- traefik.yaml
> chore(traefik): disable old tls and ciphers
